### ISSUE TITLE
How can I install this without Composer?

### ISSUE THREAD

**Issue by iamdave210** [WhichBrowser/Parser#54]
Composer isn't available to me and our ITS department won't install it. I've uploaded all the files to the server but I don't know which ones to include in my script. 
Thanks!

**Comment by ThaDafinser** [comment]
@iamdave210 that's sad to hear...

But installing it without composer is easy as well (this works for all composer based packages the same, if they can be used standalone)

You just need to define a custom autoloader http://php.net/manual/en/function.spl-autoload-register.php

The Namespace you find here https://github.com/WhichBrowser/Parser/blob/master/composer.json#L23

**Comment by NielsLeenheer** [comment]
Running this library without Composer is unsupported, but you could try including the bootstrap.php file.
