### ISSUE TITLE
New method `isMobile()`

### ISSUE THREAD

**Issue by ThaDafinser** [WhichBrowser/Parser#55]
Hi,

would it be possible, to create a new method `isMobile()` ?

Currently we got this implemented here, but such vendor specific code is always dangerous (since it can change) and if it's a internal method, you will know when you add a new type to change it also.

https://github.com/ThaDafinser/UserAgentParser/blob/master/src/Provider/WhichBrowser.php#L203

**Comment by NielsLeenheer** [comment]
Done! Added `isMobile()` in commit fd630080e094d88e522c139394998e5afc167bfc

**Comment by ThaDafinser** [comment]
Thank you :+1:
