### ISSUE TITLE
"You are using an unknown browser that imitates Opera 12"

### ISSUE THREAD

**Issue by uahim** [WhichBrowser/Parser#56]
imitates, is that a bug or a feature?
this comes up when actually using Opera 12 on WinXP SP3 and Win7 64bit.

**Comment by NielsLeenheer** [comment]
Could post the exact user agent string that causes this result?

**Comment by uahim** [comment]
Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.17

Opera/9.80 (Windows NT 5.1) Presto/2.12.388 Version/12.16

**Comment by NielsLeenheer** [comment]
You are using an unknown browser that imitates Opera 12.16 on Windows 8
````
Opera/9.80 (Windows NT 6.2; Win64; x64) Presto/2.12.388 Version/12.16
````

**Comment by NielsLeenheer** [comment]
Found the bug and will be fixed in the next release
