### ISSUE TITLE
browser detected is not work in iOS device

### ISSUE THREAD

**Issue by fanrong33** [WhichBrowser/Parser#62]
// iPhone 4
$user_agent = 'Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_2_1 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8C148 Safari/6533.18.5';
// iPhone 5
$user_agent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X; en-us) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53';
// iPhone 6
// $user_agent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4';
// iPhone 6 Plus
// $user_agent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 8_0 like Mac OS X) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Mobile/12A4345d Safari/600.1.4';
// iPad mini
$user_agent = 'Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53';

echo $result->browser->toString();
// is empty, expect  Safari

these all user_agent is from PC Chrome Developer Tools.

**Comment by ThaDafinser** [comment]
@fanrong33 those are all detected correctly.

Maybe you use an old version or have a miss configuration? You can try them here
https://whichbrowser.net/tryout/

**Comment by NielsLeenheer** [comment]
I'm not seeing any issues with these user agent strings. I'm closing this bug report.

@fanrong33 If you still have any problems, please reopen, but then I do need some more information to figure out which problems your are running into.
