### ISSUE TITLE
Google Page Speed Insights User Agents

### ISSUE THREAD

**Issue by mmuckermann-c24** [WhichBrowser/Parser#63]
The UA's used by Google Page Speed Insights analysis are correctly detected as bots,
but the device type is not being set

**_Desktop_**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36

**_Mobile_**
Mozilla/5.0 (iPhone; CPU iPhone OS 6_0_1 like Mac OS X) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Version/6.0 Mobile/10A525 Safari/8536.25

**Comment by ThaDafinser** [comment]
I think this needs a "major" rewrite and is not possible currently.

I don't know any parser which currently seperates between normal bots and mobile bots.

But it could still be a useful information

**Comment by NielsLeenheer** [comment]
Agreed, this might be useful information. But right now this is not possible.

One other possible approach would be an option to turn off bot detection altogether. That way they would fool the parser deliberately and be categorised as a desktop and mobile device.

**Comment by NielsLeenheer** [comment]
Added an option to disable bots. Included in release 2.0.18.
