### ISSUE TITLE
Nokia lumia

### ISSUE THREAD

**Issue by ThaDafinser** [WhichBrowser/Parser#64]
it seems that this should be detected as mobile, but currently it shows desktop

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+ARM%3B+Lumia+930%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F46.0.2486.0+Safari%2F537.36+Edge%2F13.10586

https://github.com/serbanghita/Mobile-Detect/issues/516

**Comment by NielsLeenheer** [comment]
WhichBrowser detection could be improved here, but this is a tricky user agent string.

This is a Lumia phone running in Continuum mode. Basically it is connected to an external monitor, keyboard and mouse and it runs the "desktop version" of Windows 10 with the desktop version of Edge. So I would actually say this is a desktop device. 

But in any case, the model and manufacturer could be added.

**Comment by NielsLeenheer** [comment]
Model and manufacturer are now properly detected. The operating system is now also detected as Windows Phone 10. But the device type is still desktop.

**Comment by NielsLeenheer** [comment]
Fixed, will be included in the next update!
