### ISSUE TITLE
HP Tablet

### ISSUE THREAD

**Issue by ThaDafinser** [WhichBrowser/Parser#66]
This is a UA of a HP tablet in our company.

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+6.3%3B+Win64%3B+x64%3B+Trident%2F7.0%3B+Touch%3B+rv%3A11.0%29+like+Gecko

Dunno how the others detect it as tablet, but i guess based on the `Touch` string

**Comment by NielsLeenheer** [comment]
Yeah, this one is tricky. 

The others probably look at `Touch` and consider that proof of being a tablet. But that is just an indication of having a touch screen. That does not mean it is a tablet. There are many Windows laptops that have touch screens. So basically it is impossible to tell from looking at the UA if this is a tablet or a laptop.

**Comment by ThaDafinser** [comment]
Yeah it's really a tricky one...can be a desktop as well like you said.
The only thing you could set 100% is a `isTouch` flag...

Also that kind of tablet is really bad - You could even start the IE in desktop modus, there you not have any other flag left.

https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

> IE11 for the desktop on 64-bit Windows 8.1 Update
> Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
