### ISSUE TITLE
Android is wrongly detected as OS when Jquery ajax call is used

### ISSUE THREAD

**Issue by sebpatu** [WhichBrowser/Parser#70]
As BrowserId will always detect an Android OS each time  X-Requested-With header is sent,
we have false positive result when we have a JQuery ajax call.

Indeed, ajax call will sent same header with XMLHttRequest value.

BrowserId should make an exception for this header value.
and some more tests are needed to understand what happens when a JQuery ajax call is made from an Android device.

Thanks

**Comment by NielsLeenheer** [comment]
From looking the source of jQuery, the value is always `XMLHttpRequest`:
https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/ajax/xhr.js#L65

**Comment by NielsLeenheer** [comment]
Same thing with Prototype:
https://github.com/sstephenson/prototype/blob/560bb59414fc9343ce85429b91b1e1b82fdc6812/src/prototype/ajax/request.js#L233

**Comment by NielsLeenheer** [comment]
The solution should be simple. WhichBrowser needs to ignore this header if it contains the value: `XMLHttpRequest`
