### ISSUE TITLE
please add alipay ua

### ISSUE THREAD

**Issue by halleystar** [WhichBrowser/Parser#77]
need alipay ua
demo:
Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Mobile/14D27 ChannelId(11) Nebula PSDType(1) AlipayDefined(nt:WIFI,ws:375|647|2.0) AliApp(AP/10.0.3.020920) AlipayClient/10.0.3.020920 Alipay Language/zh-Hans

**Comment by NielsLeenheer** [comment]
Added in commit 12e7ad66c39d55d8d9e28767c819f2e67b59e80d

**Comment by NielsLeenheer** [comment]
Included in v2.0.25

**Comment by halleystar** [comment]
ok thanks
