### ISSUE TITLE
error with WINJOY

### ISSUE THREAD

**Issue by jaggman** [WhichBrowser/Parser#79]
Hi,
I'd like to parse UA
`Mozilla/5.0 (Windows NT 6.2; ARM; Trident/7.0; Touch; rv:11.0; WPDesktop; WINJOY) like Gecko`
but something went wrong (:
`Undefined offset: 2 in /var/www/whichbrowser.net/web/vendor/whichbrowser/parser/src/Analyser/Header/Useragent/Os.php on line 968`
<img width="973" alt="2017-03-21 22 48 28" src="https://cloud.githubusercontent.com/assets/8417537/24167650/8864c186-0e88-11e7-9b15-973a59cdc4b5.png">

**Comment by jaggman** [comment]
Could you release a new version with [this fix](https://github.com/WhichBrowser/Parser/pull/80)?)

**Comment by NielsLeenheer** [comment]
I'm very close to a new release. Should be within a day or two.

**Comment by NielsLeenheer** [comment]
Included in v2.0.25
